/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as testingTokenSol from "./TestingToken.sol";

export type { testingTokenSol };
export type { TestingContract } from "./TestingContract";
