/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testingTokenSol from "./TestingToken.sol";
export { TestingContract__factory } from "./TestingContract__factory";
